This should work

diff --git a/.github/workflows/video.yml b/.github/workflows/video.yml
--- a/.github/workflows/video.yml
+++ b/.github/workflows/video.yml
@@ -40,8 +40,6 @@ jobs:
           gem install bundler
           bundle config path vendor/bundle
           bundle install --jobs 4 --retry 3
-      # TODO: only rebuild recently touched videos
-      # git diff $(git log -1 --before=@{2.days.ago} --format=%H) --name-only | filter-for-video | rebuild
       - name: Install wkhtmltopdf
         run: |
           sudo apt-get update
@@ -56,22 +54,36 @@ jobs:
           gem install bundler
           JEKYLL_ENV=production bundle exec jekyll build --strict_front_matter -d _site/training-material
 
+      # We get the previous build ID to know how many videos were changed since
+      # then.
+      #
+      # We *could* fetch the diff in the past N days but if a build fails for
+      # any reason, we'd lose those changes permanently and things would never
+      # get built.
+      #
+      # So instead we just track the last successfully built git commit.
+      - name: Previous build ID
+        id: build_id
+        run: |
+          echo "::set-output name=commit::$(curl https://galaxy-training.s3.amazonaws.com/videos/topics/last-commit -f 2>/dev/null || echo none)"
+
+      # The actual compilation process deposits everything in the ./videos/ folder.
       - name: Build Videos
         run: |
-          env | grep AWS | grep -vi secret
           xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" bash bin/ari-make.sh
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_POLLY_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_POLLY_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
+          PREVIOUS_COMMIT_ID: ${{ steps.build_id.outputs.commit }}
 
       # Deploy step, scary.
-      #- uses: jakejarvis/s3-sync-action@v0.5.1
-        #with:
-          #args: --acl public-read --follow-symlinks
-        #env:
-          #AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
-          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          #SOURCE_DIR: './videos/topics'
-          #DEST_DIR: '/videos/topics/'
+      - uses: jakejarvis/s3-sync-action@v0.5.1
+        with:
+          args: --acl public-read --follow-symlinks
+        env:
+          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          SOURCE_DIR: './videos/topics'
+          DEST_DIR: '/videos/topics/'
